### ISSUE TITLE
Touchscreen support is needed.

### ISSUE THREAD

**Issue by KOLANICH** [shtange/catch-the-egg#7]

**Comment by jevgenig** [comment]
Implemented in https://github.com/shtange/catch-the-egg/pull/11

**Comment by shtange** [comment]
Done

**Comment by KOLANICH** [comment]
The current ui is bad. I think that
1 we dont need the buttons (they are too small), instead of them the screen should be partitioned into 4 zones
2 we need a restart button

**Comment by shtange** [comment]
Buttons is a promise to the ui original game
+ increased active area (buttons)
+ added the Restart button

**Comment by KOLANICH** [comment]
>Buttons is a promise to the ui original game
You can draw the buttons but process taps on the quarters of the screen (the boundary should ie between the buttons) .
